### ISSUE TITLE
Is the plugin working?

### ISSUE THREAD

**Issue by gurabli** [gala132/nCoreCouchPotatoProvider#11]
Hi,
I followed the instructions, but for some reason it is not working. I will be able to provide logs later, as I'm reinstalling my server, but I would like to ask if you could confirm that the plugin is working as it should now, so the problem is probably on my side.
Thanks!

**Comment by gala132** [comment]
Hi!
The plugin should be working, please provide the logs, so we can see the errors you are experiencing.

**Comment by gurabli** [comment]
Many thanks for confirming that it is working, then it was something on my side. I will try to get the logs asap, but don't have the server up and running now. If I manage to find some time, I will try on Virtualbox. 

P.S.: I would like to ask you something, but would be better in email or pm, can I send you an email that you have configured here at github?

**Comment by gala132** [comment]
Hi!
It is a noreply address, please use the contact form on the linked site.
You will find it in the navigation bar.
