### ISSUE TITLE
Extra score in advanced settings

### ISSUE THREAD

**Issue by ohmano** [gala132/nCoreCouchPotatoProvider#8]
Hello,

Nem lenne rossz egy extra_score mező még, mert így jelenleg ezek kb 300-400-as score-t kapnak, míg a nagy torrent oldalakról akár 2000 is lehet.
Ha lehetne extra score akkor mindenképpen a magyarok kerülnének előre és azokat szedné le.

Új vagyok Couchpotato-ban, ha erre van más megoldás, akkor bocs :)

{
                    'name': 'extra_score',
                    'advanced': True,
                    'label': 'Extra Score',
                    'type': 'int',
                    'default': 0,
                    'description': 'Starting score for each release found via this provider.',
                }

**Comment by gala132** [comment]
Ha megmondod mi szerint kéne ezt a "Score" mezőt generálni vagy kiírni akkor elgondolkozhatunk erről.

**Comment by ohmano** [comment]
Bocs, nem volt teljes a leírásom .

Szóval ugye minden torrent kap egy Score-t ami alapján aztán majd a CP berakja azt a letöltéseid közé.
![2015-05-13_1459](https://cloud.githubusercontent.com/assets/5798619/7611947/f2795090-f987-11e4-894c-3f8327733c95.png)

Ahhoz, hogy nekem tényleg az nCore-ról szedje le a cuccot, ahhoz meg kell emelnem a score-ját.
Ehhez kell ez az extra score tag az init.py-ba.
![2015-05-13_1550](https://cloud.githubusercontent.com/assets/5798619/7611988/32f40d72-f988-11e4-941f-e062b9f4a689.png)

**Comment by gala132** [comment]
Értem.
Szóval ez a prioritásra volna, minél nagyobb ez a kezdőérték, annál előrébb hozza a találatok között, ha több trackeren keresi?

**Comment by ohmano** [comment]
Úgy ahogy mondod :)

**Comment by ohmano** [comment]
Loorant pull request-je eredményeképpen lezárom ezeket az issue-kat :)
